services:
  app:
    build:
      context: .
      dockerfile : ./docker/Dockerfile
      args:
        UID: "$UID"
        GID: "$GID"
    container_name: app
    user: "user"
    tty: true
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./template_python:/src/template_python
      - ./log:/log
    command: bash -c "python -m pip install -q -e /src/ && python /src/template_python/main.py"

