name: test

on:
  push: # any branch
  pull_request:
    branches: [main]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Dependency
        run: |
          pip install poetry
          poetry install
      - name: Lint with ruff
        run: |
          ruff .
      - name: Formatting
        run: |
          mypy . --strict --platform win32
          mypy . --strict --platform linux
          mypy . --strict --platform darwin
          isort -c .
          black .
